inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# Style/ClassAndModuleChildren disable only for test files
Style/ClassAndModuleChildren:
  AllowConsecutiveConditionals: true